apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    name: demo
    owner: et
    project: cloudprem
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    owner: et
    project: cloudprem
